repos:
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.5
  hooks:
  - id: autopep8
    args:
      - --in-place
      - --aggressive
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: flake8
