version: 0.0
os: linux
files:
  - source: ./
    destination: /data/app/zodiac/pisces
permissions:
  - object: /data/app/zodiac/
    owner: apache
    group: apache
hooks:
  AfterInstall:
    - location: deploy_scripts/install_dependencies.sh
      timeout: 300
      runas: apache
    - location: deploy_scripts/set_env.sh
      timeout: 300
      runas: apache
    - location: deploy_scripts/run_management_commands.sh
      timeout: 300
      runas: apache
  ApplicationStart:
    - location: deploy_scripts/application_start.sh
      timeout: 20
      runas: root
  ValidateService:
    - location: deploy_scripts/validate_service.sh
      timeout: 10
      runas: root
