# Generated by Django 2.2.10 on 2020-03-04 02:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_id', models.CharField(max_length=255)),
                ('object_type', models.CharField(choices=[('agent', 'Agent'), ('collection', 'Collection'), ('object', 'Object'), ('term', 'Term')], max_length=255)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('indexed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
