# Generated by Django 2.2.10 on 2020-06-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0002_auto_20200419_1936'),
    ]

    def add_uri(apps, schema_editor):
        DataObject = apps.get_model('transformer', 'DataObject')
        for obj in DataObject.objects.all():
            uri = obj.data.get("uri") if obj.data.get("uri") else obj.data.external_identifiers[0].identifier
            obj.uri = uri
            obj.save()

    def reverse_add(apps, schema_editor):
        pass

    operations = [
        migrations.RemoveIndex(
            model_name='dataobject',
            name='data_gin',
        ),
        migrations.AddField(
            model_name='dataobject',
            name='uri',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.RunPython(add_uri, reverse_add),
        migrations.AlterField(
            model_name='dataobject',
            name='uri',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
