# Generated by Django 2.0.13 on 2019-04-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0003_transformrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
