# Generated by Django 2.0.13 on 2019-04-10 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0004_object_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcedata',
            name='source',
            field=models.CharField(choices=[(0, 'Aurora'), (1, 'Archivematica'), (2, 'Fedora'), (3, 'ArchivesSpace')], max_length=100),
        ),
        migrations.AlterField(
            model_name='transformrun',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
