# Generated by Django 2.0.13 on 2019-04-10 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0005_auto_20190409_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transformer.Agent'),
        ),
        migrations.AddField(
            model_name='date',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transformer.Collection'),
        ),
        migrations.AddField(
            model_name='date',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transformer.Object'),
        ),
    ]
