# Generated by Django 2.0.13 on 2019-04-10 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0006_auto_20190409_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='begin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
