# Generated by Django 2.0.13 on 2019-04-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0007_auto_20190409_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identifier',
            name='source',
            field=models.CharField(choices=[(0, 'Aurora'), (1, 'Archivematica'), (2, 'Fedora'), (3, 'ArchivesSpace'), (4, 'Pisces')], max_length=100),
        ),
    ]
