# Generated by Django 2.0.13 on 2019-04-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0009_auto_20190410_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rightsstatement',
            name='dateStart',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rightsstatement',
            name='determinationDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
