# Generated by Django 2.0.13 on 2019-04-11 12:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0011_auto_20190411_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='tree',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
