# Generated by Django 2.0.13 on 2019-04-13 04:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0012_collection_tree'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subnote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Text'), ('orderedlist', 'Ordered List'), ('definedlist', 'Defined List')], max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('content', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='TransformRunError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=255)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transformer.TransformRun')),
            ],
        ),
        migrations.RemoveField(
            model_name='note',
            name='content',
        ),
        migrations.AddField(
            model_name='subnote',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transformer.Note'),
        ),
    ]
