# Generated by Django 2.0.13 on 2019-04-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0014_auto_20190415_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identifier',
            name='source',
            field=models.CharField(choices=[(0, 'Aurora'), (1, 'Archivematica'), (2, 'Fedora'), (3, 'ArchivesSpace'), (4, 'Pisces'), (5, 'Cartographer')], max_length=100),
        ),
    ]
