# Generated by Django 2.0.13 on 2019-04-15 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0015_auto_20190415_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='parents',
        ),
        migrations.RemoveField(
            model_name='object',
            name='parents',
        ),
        migrations.AddField(
            model_name='collection',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transformer.Collection'),
        ),
        migrations.AddField(
            model_name='object',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transformer.Collection'),
        ),
    ]
