# Generated by Django 2.0.13 on 2019-04-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0017_auto_20190415_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='type',
            field=models.CharField(choices=[('accessrestrict', 'Conditions Governing Access'), ('accruals', 'Accruals'), ('acqinfo', 'Immediate Source of Acquisition'), ('altformavail', 'Existence and Location of Copies'), ('appraisal', 'Appraisal'), ('arrangement', 'Arrangement'), ('bibliography', 'Bibliography'), ('bioghist', 'Biographical / Historical'), ('custodhist', 'Custodial History'), ('fileplan', 'File Plan'), ('index', 'Index'), ('odd', 'General'), ('otherfindaid', 'Other Finding Aids'), ('originalsloc', 'Existence and Location of Originals'), ('phystech', 'Physical Characteristics and Technical Requirements'), ('prefercite', 'Preferred Citation'), ('processinfo', 'Processing Information'), ('relatedmaterial', 'Related Archival Materials'), ('scopecontent', 'Scope and Contents'), ('separatedmaterial', 'Separated Materials'), ('userestrict', 'Conditions Governing Use'), ('dimensions', 'Dimensions'), ('legalstatus', 'Legal Status'), ('summary', 'Summary'), ('edition', 'Edition'), ('extent', 'Extent'), ('note', 'General Note'), ('inscription', 'Inscription'), ('langmaterial', 'Language of Materials'), ('physdesc', 'Physical Description'), ('relatedmaterial', 'Related Materials'), ('abstract', 'Abstract'), ('physloc', 'Physical Location'), ('materialspec', 'Materials Specific Details'), ('physfacet', 'Physical Facet'), ('rights_statement', 'Rights'), ('rights_statement_act', 'Acts'), ('materials', 'Materials'), ('type_note', 'Type Note'), ('additional_information', 'Additional Information'), ('expiration', 'Expiration'), ('extension', 'Extension'), ('permissions', 'Permissions'), ('restrictions', 'Restrictions')], max_length=100),
        ),
    ]
