# Generated by Django 2.0.13 on 2019-04-17 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0018_auto_20190415_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='tree',
            new_name='source_tree',
        ),
    ]
