# Generated by Django 2.0.13 on 2019-04-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0019_auto_20190417_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='tree_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='tree_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
