# Generated by Django 2.0.13 on 2019-04-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0020_auto_20190421_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformrun',
            name='source',
            field=models.CharField(choices=[(0, 'Aurora'), (1, 'Archivematica'), (2, 'Fedora'), (3, 'ArchivesSpace'), (4, 'Pisces'), (5, 'Cartographer'), (6, 'Trees')], max_length=100),
        ),
    ]
