# Generated by Django 2.0.13 on 2019-04-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0021_auto_20190421_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformrun',
            name='object_type',
            field=models.CharField(blank=True, choices=[('agents', 'Agents'), ('collections', 'Collections'), ('objects', 'Objects'), ('terms', 'Terms')], max_length=100, null=True),
        ),
    ]
