# Generated by Django 2.0.13 on 2019-04-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0022_transformrun_object_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sourcedata',
            name='source',
            field=models.CharField(choices=[(0, 'Aurora'), (1, 'Archivematica'), (2, 'Fedora'), (3, 'ArchivesSpace'), (4, 'Cartographer'), (5, 'Wikidata')], max_length=100),
        ),
    ]
