# Generated by Django 2.0.13 on 2019-04-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0023_auto_20190429_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='wikipedia_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='source',
            field=models.CharField(choices=[(0, 'Aurora'), (1, 'Archivematica'), (2, 'Fedora'), (3, 'ArchivesSpace'), (4, 'Pisces'), (5, 'Cartographer'), (6, 'Wikidata')], max_length=100),
        ),
        migrations.AlterField(
            model_name='transformrun',
            name='source',
            field=models.CharField(choices=[(0, 'Aurora'), (1, 'Archivematica'), (2, 'Fedora'), (3, 'ArchivesSpace'), (4, 'Pisces'), (5, 'Cartographer'), (6, 'Trees'), (7, 'Wikidata')], max_length=100),
        ),
    ]
