# Generated by Django 2.0.13 on 2019-05-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0025_auto_20190430_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
