# Generated by Django 2.0.13 on 2019-05-14 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0026_auto_20190430_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='source',
            field=models.CharField(choices=[(1, 'ArchivesSpace'), (2, 'Cartographer'), (3, 'Wikidata'), (4, 'Wikipedia')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='identifier',
            name='source',
            field=models.CharField(choices=[(1, 'ArchivesSpace'), (2, 'Cartographer'), (3, 'Wikidata'), (4, 'Wikipedia')], max_length=100),
        ),
        migrations.AlterField(
            model_name='sourcedata',
            name='source',
            field=models.CharField(choices=[(1, 'ArchivesSpace'), (2, 'Cartographer'), (3, 'Wikidata'), (4, 'Wikipedia')], max_length=100),
        ),
        migrations.AlterField(
            model_name='transformrun',
            name='source',
            field=models.CharField(choices=[(1, 'ArchivesSpace'), (2, 'Cartographer'), (3, 'Wikidata'), (4, 'Wikipedia')], max_length=100),
        ),
    ]
