# Generated by Django 2.0.13 on 2019-05-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0027_fetchrun_fetchrunerror'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetchrun',
            name='object_type',
            field=models.CharField(blank=True, choices=[('agents', 'Agents'), ('resources', 'Resources'), ('objects', 'Objects'), ('terms', 'Terms')], max_length=100, null=True),
        ),
    ]
