# Generated by Django 2.0.13 on 2019-05-15 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0028_auto_20190509_1439'),
        ('transformer', '0027_auto_20190513_2058'),
    ]

    operations = [
    ]
