# Generated by Django 2.0.13 on 2019-05-15 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0029_merge_20190515_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='wikidata_id',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='wikipedia_url',
        ),
    ]
