# Generated by Django 2.0.10 on 2019-04-02 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identifiers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalidentifier',
            name='identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identifiers', to='identifiers.Identifier'),
        ),
    ]
