"""
Django settings for pisces project.

Generated by 'django-admin startproject' using Django 2.0.10.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("PISCES_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = int(os.environ.get("PISCES_DEBUG", default=0))

ALLOWED_HOSTS = os.environ.get("PISCES_DJANGO_ALLOWED_HOSTS").split(" ")

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'health_check',
    'fetcher',
    'merger',
    'transformer',
    'silk',
    'django_cron',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'silk.middleware.SilkyMiddleware',
]

ROOT_URLCONF = 'pisces.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'transformer', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pisces.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.environ.get("PISCES_SQL_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.environ.get("PISCES_SQL_DATABASE", os.path.join(BASE_DIR, "db.sqlite3")),
        "USER": os.environ.get("PISCES_SQL_USER", "user"),
        "PASSWORD": os.environ.get("PISCES_SQL_PASSWORD", "password"),
        "HOST": os.environ.get("PISCES_SQL_HOST", "localhost"),
        "PORT": int(os.environ.get("PISCES_SQL_PORT", "5432")),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = "fetcher.User"

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.environ.get("PISCES_DJANGO_STATIC_ROOT", os.path.join(BASE_DIR, "static"))

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 25
}

# Silk Profiling
SILKY_PYTHON_PROFILER = int(os.environ.get("PISCES_SILKY_PYTHON_PROFILER", default=0))

# Django cron settings
CRON_CLASSES = [
    "fetcher.cron.FetchAgents",
]
DJANGO_CRON_LOCK_BACKEND = "django_cron.backends.lock.cache.CacheLock"

ARCHIVESSPACE = {
    "baseurl": os.environ.get("PISCES_AS_BASEURL", default="http://sandbox.archivesspace.org/api"),
    "username": os.environ.get("PISCES_AS_USERNAME", default="admin"),
    "password": os.environ.get("PISCES_AS_PASSWORD", default="admin"),
    "repo": os.environ.get("PISCES_AS_REPO_ID", default=2),
}

CARTOGRAPHER = {
    "baseurl": os.environ.get("PISCES_CARTOGRAPHER_BASEURL", default="http://192.168.50.27:8000"),
    "user": os.environ.get("PISCES_CARTOGRAPHER_USER", default="admin"),
    "password": os.environ.get("PISCES_CARTOGRAPHER_PASSWORD", default="admin"),
    "health_check_path": os.environ.get("PISCES_CARTOGRAPHER_HEALTH_CHECK_PATH", default="/status/health/"),
}

INDEX_DELETE_URL = os.environ.get("PISCES_INDEX_DELETE_URL")
