# Generated by Django 2.2.6 on 2020-02-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0002_auto_20200201_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetchrunerror',
            name='message',
            field=models.TextField(max_length=255),
        ),
    ]
