# Generated by Django 2.2.10 on 2020-02-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0003_auto_20200201_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetchrun',
            name='object_status',
            field=models.CharField(choices=[('updated', 'Updated'), ('deleted', 'Deleted')], default='updated', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fetchrun',
            name='object_type',
            field=models.CharField(choices=[('resource', 'Resource'), ('archival_object', 'Archival Object'), ('subject', 'Subject'), ('person', 'Person'), ('organization', 'Organization'), ('family', 'Family'), ('arrangement_map', 'Arrangement Map')], default='resource', max_length=100),
            preserve_default=False,
        ),
    ]
