# Generated by Django 2.2.10 on 2020-03-04 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0004_auto_20200225_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fetchrunerror',
            options={'ordering': ('datetime',)},
        ),
    ]
