# Generated by Django 2.2.10 on 2020-03-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0006_auto_20200304_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetchrun',
            name='object_type',
            field=models.CharField(choices=[('resource', 'Resource'), ('archival_object', 'Archival Object'), ('subject', 'Subject'), ('agent_person', 'Person'), ('agent_corporate_entity', 'Organization'), ('agent_family', 'Family'), ('arrangement_map_component', 'Arrangement Map Component')], max_length=100),
        ),
    ]
