AGENT_RELATOR_CHOICES = (
    ('abr', ' Abridger'),
    ('act', ' Actor'),
    ('adi', ' Art director'),
    ('adp', ' Adapter'),
    ('anl', ' Analyst'),
    ('anm', ' Animator'),
    ('ann', ' Annotator'),
    ('ape', ' Appellee'),
    ('apl', ' Appellant'),
    ('app', ' Applicant'),
    ('arc', ' Architect'),
    ('arr', ' Arranger'),
    ('acp', ' Art copyist'),
    ('art', ' Artist'),
    ('ard', ' Artistic director'),
    ('asg', ' Assignee'),
    ('asn', ' Associated name'),
    ('att', ' Attributed name'),
    ('auc', ' Auctioneer'),
    ('aut', ' Author'),
    ('aqt', ' Author in quotations or text abstracts'),
    ('aft', ' Author of afterword, colophon, etc.'),
    ('aud', ' Author of dialog'),
    ('aui', ' Author of introduction, etc.'),
    ('aus', ' Author of screenplay, etc.'),
    ('ato', ' Autographer'),
    ('ant', ' Bibliographic antecedent'),
    ('bnd', ' Binder'),
    ('bdd', ' Binding designer'),
    ('blw', ' Blurb writer'),
    ('bkd', ' Book designer'),
    ('bkp', ' Book producer'),
    ('bjd', ' Bookjacket designer'),
    ('bpd', ' Bookplate designer'),
    ('bsl', ' Bookseller'),
    ('brl', ' Braille embosser'),
    ('brd', ' Broadcaster'),
    ('cll', ' Calligrapher'),
    ('ctg', ' Cartographer'),
    ('cas', ' Caster'),
    ('cns', ' Censor'),
    ('chr', ' Choreographer'),
    ('cng', ' Cinematographer'),
    ('cli', ' Client'),
    ('cor', ' Collection registrar'),
    ('clb', ' Collaborator'),
    ('col', ' Collector'),
    ('clt', ' Collotyper'),
    ('clr', ' Colorist'),
    ('cmm', ' Commentator'),
    ('cwt', ' Commentator for written text'),
    ('com', ' Compiler'),
    ('cpl', ' Complainant'),
    ('cpt', ' Complainant-appellant'),
    ('cpe', ' Complainant-appellee'),
    ('cmp', ' Composer'),
    ('cmt', ' Compositor'),
    ('ccp', ' Conceptor'),
    ('cnd', ' Conductor'),
    ('con', ' Conservator'),
    ('csl', ' Consultant'),
    ('csp', ' Consultant to a project'),
    ('cos', ' Contestant'),
    ('cot', ' Contestant-appellant'),
    ('coe', ' Contestant-appellee'),
    ('cts', ' Contestee'),
    ('ctt', ' Contestee-appellant'),
    ('cte', ' Contestee-appellee'),
    ('ctr', ' Contractor'),
    ('ctb', ' Contributor'),
    ('cpc', ' Copyright claimant'),
    ('cph', ' Copyright holder'),
    ('crr', ' Corrector'),
    ('crp', ' Correspondent'),
    ('cst', ' Costume designer'),
    ('cou', ' Court governed'),
    ('crt', ' Court reporter'),
    ('cov', ' Cover designer'),
    ('cre', ' Creator'),
    ('cur', ' Curator of an exhibition'),
    ('dnc', ' Dancer'),
    ('dtc', ' Data contributor'),
    ('dtm', ' Data manager'),
    ('dte', ' Dedicatee'),
    ('dto', ' Dedicator'),
    ('dfd', ' Defendant'),
    ('dft', ' Defendant-appellant'),
    ('dfe', ' Defendant-appellee'),
    ('dgg', ' Degree grantor'),
    ('dgs', ' Degree supervisor'),
    ('dln', ' Delineator'),
    ('dpc', ' Depicted'),
    ('dpt', ' Depositor'),
    ('dsr', ' Designer'),
    ('drt', ' Director'),
    ('dis', ' Dissertant'),
    ('dbp', ' Distribution place'),
    ('dst', ' Distributor'),
    ('dnr', ' Donor'),
    ('drm', ' Draftsman'),
    ('dub', ' Dubious author'),
    ('edt', ' Editor'),
    ('edc', ' Editor of compilation'),
    ('edm', ' Editor of moving image work'),
    ('elg', ' Electrician'),
    ('elt', ' Electrotyper'),
    ('enj', ' Enacting jurisdiction'),
    ('eng', ' Engineer'),
    ('egr', ' Engraver'),
    ('etr', ' Etcher'),
    ('evp', ' Event place'),
    ('exp', ' Appraiser'),
    ('fac', ' Facsimilist'),
    ('fld', ' Field director'),
    ('fmd', ' Film director'),
    ('fds', ' Film distributor'),
    ('flm', ' Film editor'),
    ('fmp', ' Film producer'),
    ('fmk', ' Filmmaker'),
    ('fpy', ' First party'),
    ('frg', ' Forger'),
    ('fmo', ' Former owner'),
    ('fnd', ' Funder'),
    ('gis', ' Geographic information specialist'),
    ('grt', ' Graphic technician'),
    ('hnr', ' Honoree'),
    ('hst', ' Host'),
    ('his', ' Host institution'),
    ('ilu', ' Illuminator'),
    ('ill', ' Illustrator'),
    ('ins', ' Inscriber'),
    ('itr', ' Instrumentalist'),
    ('ive', ' Interviewee'),
    ('ivr', ' Interviewer'),
    ('inv', ' Inventor'),
    ('isb', ' Issuing body'),
    ('jud', ' Judge'),
    ('jug', ' Jurisdiction governed'),
    ('lbr', ' Laboratory'),
    ('ldr', ' Laboratory director'),
    ('lsa', ' Landscape architect'),
    ('led', ' Lead'),
    ('len', ' Lender'),
    ('lil', ' Libelant'),
    ('lit', ' Libelant-appellant'),
    ('lie', ' Libelant-appellee'),
    ('lel', ' Libelee'),
    ('let', ' Libelee-appellant'),
    ('lee', ' Libelee-appellee'),
    ('lbt', ' Librettist'),
    ('lse', ' Licensee'),
    ('lso', ' Licensor'),
    ('lgd', ' Lighting designer'),
    ('ltg', ' Lithographer'),
    ('lyr', ' Lyricist'),
    ('mfp', ' Manufacture place'),
    ('mfr', ' Manufacturer'),
    ('mrb', ' Marbler'),
    ('mrk', ' Markup editor'),
    ('med', ' Medium'),
    ('mdc', ' Metadata contact'),
    ('mte', ' Metal-engraver'),
    ('mtk', ' Minute taker'),
    ('mod', ' Moderator'),
    ('mon', ' Monitor'),
    ('mcp', ' Music copyist'),
    ('msd', ' Musical director'),
    ('mus', ' Musician'),
    ('nrt', ' Narrator'),
    ('osp', ' Onscreen presenter'),
    ('opn', ' Opponent'),
    ('orm', ' Organizer of meeting'),
    ('org', ' Originator'),
    ('oth', ' Other'),
    ('own', ' Owner'),
    ('pan', ' Panelist'),
    ('ppm', ' Papermaker'),
    ('pta', ' Patent applicant'),
    ('pth', ' Patentee'),
    ('pat', ' Patron'),
    ('prf', ' Performer'),
    ('pma', ' Permitting agency'),
    ('pht', ' Photographer'),
    ('ptf', ' Plaintiff'),
    ('ptt', ' Plaintiff-appellant'),
    ('pte', ' Plaintiff-appellee'),
    ('plt', ' Platemaker'),
    ('pra', ' Praeses'),
    ('pre', ' Presenter'),
    ('prt', ' Printer'),
    ('pop', ' Printer of plates'),
    ('prm', ' Printmaker'),
    ('prc', ' Process contact'),
    ('pro', ' Producer'),
    ('prn', ' Production company'),
    ('pmn', ' Production manager'),
    ('prs', ' Production designer'),
    ('prd', ' Production personnel'),
    ('prp', ' Production place'),
    ('prg', ' Programmer'),
    ('pdr', ' Project director'),
    ('pfr', ' Proofreader'),
    ('prv', ' Provider'),
    ('pup', ' Publication place'),
    ('pbl', ' Publisher'),
    ('pbd', ' Publishing director'),
    ('ppt', ' Puppeteer'),
    ('rdd', ' Radio director'),
    ('rpc', ' Radio producer'),
    ('rcp', ' Recipient'),
    ('rce', ' Recording engineer'),
    ('rcd', ' Recordist'),
    ('red', ' Redaktor'),
    ('ren', ' Renderer'),
    ('rpt', ' Reporter'),
    ('rps', ' Repository'),
    ('rth', ' Research team head'),
    ('rtm', ' Research team member'),
    ('res', ' Researcher'),
    ('rsp', ' Respondent'),
    ('rst', ' Respondent-appellant'),
    ('rse', ' Respondent-appellee'),
    ('rpy', ' Responsible party'),
    ('rsg', ' Restager'),
    ('rsr', ' Restorationist'),
    ('rev', ' Reviewer'),
    ('rbr', ' Rubricator'),
    ('sce', ' Scenarist'),
    ('sad', ' Scientific advisor'),
    ('scr', ' Scribe'),
    ('scl', ' Sculptor'),
    ('spy', ' Second party'),
    ('sec', ' Secretary'),
    ('sll', ' Seller'),
    ('std', ' Set designer'),
    ('stg', ' Setting'),
    ('sgn', ' Signer'),
    ('sng', ' Singer'),
    ('sds', ' Sound designer'),
    ('spk', ' Speaker'),
    ('spn', ' Sponsor'),
    ('sgd', ' Stage director'),
    ('stm', ' Stage manager'),
    ('stn', ' Standards body'),
    ('str', ' Stereotyper'),
    ('stl', ' Storyteller'),
    ('sht', ' Supporting host'),
    ('srv', ' Surveyor'),
    ('tch', ' Teacher'),
    ('tcd', ' Technical director'),
    ('tld', ' Television director'),
    ('tlp', ' Television producer'),
    ('ths', ' Thesis advisor'),
    ('trc', ' Transcriber'),
    ('trl', ' Translator'),
    ('tyd', ' Type designer'),
    ('tyg', ' Typographer'),
    ('uvp', ' University place'),
    ('vdg', ' Videographer'),
    ('vac', ' Voice actor'),
    ('voc', ' Vocalist'),
    ('wit', ' Witness'),
    ('wde', ' Wood engraver'),
    ('wdc', ' Woodcutter'),
    ('wam', ' Writer of accompanying material'),
    ('wac', ' Writer of added commentary'),
    ('wal', ' Writer of added lyrics'),
    ('wat', ' Writer of added text'),
    ('win', ' Writer of introduction'),
    ('wpr', ' Writer of preface'),
    ('wst', ' Writer of supplementary textual content')
)

AGENT_ROLE_CHOICES = (
    ('creator', 'Creator'),
    ('source', 'Source'),
    ('subject', 'Subject')
)

CONTAINER_TYPE_CHOICES = (
    ('box', 'Box'),
    ('carton', 'Carton'),
    ('card', 'Card'),
    ('case', 'Case'),
    ('Disc', 'Disc'),
    ('disk', 'Disk'),
    ('drawer', 'Drawer'),
    ('dvd', 'DVD'),
    ('envelope', 'Envelope'),
    ('folder', 'Folder'),
    ('frame', 'Frame'),
    ('item', 'Item'),
    ('object', 'Object'),
    ('package', 'Package'),
    ('page', 'Page'),
    ('reel', 'Reel'),
    ('Reel', 'Reel'),
    ('roll', 'Roll'),
    ('sheet', 'Sheet'),
    ('Tape', 'Tape'),
    ('1/4 inch audio cassette', '1/4 inch audio cassette'),
    ('volume', 'Volume')
)

DATE_TYPE_CHOICES = (
    ('single', 'Single'),
    ('inclusive', 'Inclusive'),
    ('bulk', 'Bulk'),
    ('range', 'Range')
)

DATE_LABEL_CHOICES = (
    ('agent_relation', 'Agent Relation'),
    ('broadcast', 'Broadcast'),
    ('copyright', 'Copyright'),
    ('creation', 'Creation'),
    ('deaccession', 'Deaccession'),
    ('digitized', 'Digitized'),
    ('event', 'Event'),
    ('existence', 'Existence'),
    ('issued', 'Issued'),
    ('modified', 'Modified'),
    ('publication', 'Publication'),
    ('record_keeping', 'Record Keeping'),
    ('usage', 'Usage'),
    ('other', 'Other')
)

INSTANCE_TYPE_CHOICES = (
    ('accession', 'Accession'),
    ('audio', 'Audio'),
    ('audiovisual materials', 'Audiovisual Materials'),
    ('bound volume', 'Bound Volume'),
    ('collection', 'Collection'),
    ('Digital', 'Digital'),
    ('computer_disks', 'Computer Disks'),
    ('digital_object', 'Digital Object'),
    ('documents', 'Documents'),
    ('Ephemera', 'Ephemera'),
    ('microform', 'Microform'),
    ('mixed materials', 'Mixed Materials'),
    ('moving images', 'Moving Images'),
    ('realia', 'Realia'),
    ('still image', 'Still Image'),
    ('text', 'Text')
)

LEVEL_CHOICES = (
    ('class', 'Class'),
    ('collection', 'Collection'),
    ('file', 'File'),
    ('fonds', 'Fonds'),
    ('item', 'Item'),
    ('otherlevel', 'Other Level'),
    ('recordgrp', 'Record Group'),
    ('series', 'Series'),
    ('subfonds', 'Sub-Fonds'),
    ('subgrp', 'Sub-Group'),
    ('subseries', 'Sub-Series'),
    ('unspecified', 'Unspecified')
)

NAME_SOURCE_CHOICES = (
    ('local', 'Local sources'),
    ('nad', 'NAD / ARK II Name Authority Database'),
    ('naf', 'Library of Congress Name Authority File'),
    ('ingest', 'Ingested'),
    ('ulan', 'Union List of Artist Names')
)

NAME_RULES_CHOICES = (
    ('aacr', 'Anglo-American Cataloging Rules'),
    ('dacs', 'Describing Archives: a Content Standard'),
    ('local', 'Local Rules'),
    ('rda', 'Resource Description and Access')
)

NOTE_TYPE_CHOICES = (
    ('abstract', 'Abstract'),
    ('accessrestrict', 'Conditions Governing Access'),
    ('accruals', 'Accruals'),
    ('acqinfo', 'Immediate Source of Acquisition'),
    ('additional_information', 'Additional Information'),
    ('altformavail', 'Existence and Location of Copies'),
    ('appraisal', 'Appraisal'),
    ('arrangement', 'Arrangement'),
    ('bibliography', 'Bibliography'),
    ('bioghist', 'Biographical / Historical'),
    ('custodhist', 'Custodial History'),
    ('dimensions', 'Dimensions'),
    ('edition', 'Edition'),
    ('expiration', 'Expiration'),
    ('extension', 'Extension'),
    ('extent', 'Extent'),
    ('fileplan', 'File Plan'),
    ('inscription', 'Inscription'),
    ('index', 'Index'),
    ('langmaterial', 'Language of Materials'),
    ('legalstatus', 'Legal Status'),
    ('materials', 'Materials'),
    ('materialspec', 'Materials Specific Details'),
    ('note', 'General Note'),
    ('odd', 'General'),
    ('otherfindaid', 'Other Finding Aids'),
    ('originalsloc', 'Existence and Location of Originals'),
    ('permissions', 'Permissions'),
    ('physdesc', 'Physical Description'),
    ('physfacet', 'Physical Facet'),
    ('physloc', 'Physical Location'),
    ('phystech', 'Physical Characteristics and Technical Requirements'),
    ('prefercite', 'Preferred Citation'),
    ('processinfo', 'Processing Information'),
    ('relatedmaterial', 'Related Archival Materials'),
    ('restrictions', 'Restrictions'),
    ('scopecontent', 'Scope and Contents'),
    ('separatedmaterial', 'Separated Materials'),
    ('summary', 'Summary'),
    ('type_note', 'Type Note'),
    ('userestrict', 'Conditions Governing Use'),
)

NOTE_TYPE_CHOICES_TRANSFORM = (
    ('abstract', 'Abstract'),
    ('accessrestrict', 'Conditions Governing Access'),
    ('arrangement', 'Arrangement'),
    ('bioghist', 'Biographical / Historical'),
    ('materialspec', 'Materials Specific Details'),
    ('physdesc', 'Physical Description'),
    ('processinfo', 'Processing Information'),
    ('scopecontent', 'Scope and Contents'),
    ('userestrict', 'Conditions Governing Use'),
)

REFERENCE_TYPE_CHOICES = (
    ("cultural_context", "Cultural Context"),
    ("function", "Function"),
    ("geographic", "Geographic"),
    ("genre_form", "Genre Form"),
    ("occupation", "Occupation"),
    ("style_period", "Style Period"),
    ("technique", "Technique"),
    ("temporal", "Temporal"),
    ("topical", "Topical"),
    ("person", "Person"),
    ("organization", "Organization"),
    ("family", "Family"),
    ("software", "Software"),
    ("object", "Object"),
    ("collection", "Collection"),
)

SOURCE_CHOICES = (
    ('archivesspace', 'ArchivesSpace'),
    ('cartographer', 'Cartographer'),
    ('wikidata', 'Wikidata'),
    ('wikipedia', 'Wikipedia')
)

SUBNOTE_TYPE_CHOICES = (
    ('text', 'Text'),
    ('orderedlist', 'Ordered List'),
    ('definedlist', 'Defined List'),
)

SUBJECT_SOURCE_CHOICES = (
    ('aat', 'Art & Architecture Thesaurus'),
    ('gmgpc', 'TGM II, Genre and physical characteristic terms'),
    ('ingest', 'Ingested'),
    ('lcsh', 'Library of Congress Subject Headings'),
    ('Library of Congress Subject Headings', 'Library of Congress Subject Headings'),
    ('local', 'Local sources'),
    ('mesh', 'Medical Subject Headings'),
    ('rbgenr', 'Genre Terms: A Thesaurus for Use in Rare Book and Special Collections Cataloguing'),
    ('tgn', 'Getty Thesaurus of Geographic Names')
)

TERM_TYPE_CHOICES = (
    ('cultural_context', 'Cultural context'),
    ('function', 'Function'),
    ('geographic', 'Geographic'),
    ('genre_form', 'Genre / Form'),
    ('occupation', 'Occupation'),
    ('style_period', 'Style / Period'),
    ('technique', 'Technique'),
    ('temporal', 'Temporal'),
    ('topical', 'Topical'),
)
